name: Build & Push Docker Image Action
description: Enhanced composite action for Build & Push Docker Image stage with comprehensive Jenkins feature support
inputs: {}
runs:
  using: composite
  steps:
  - name: Login to DockerHub
    uses: docker/login-action@v3
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
  - name: Build Docker image
    run: docker build -t ${IMAGE}:${BUILD_TAG} .
    shell: bash
  - name: Build Docker image
    run: docker build -t ${IMAGE}:${BUILD_TAG} .
    shell: bash
  - name: Push Docker image
    run: docker push ${IMAGE}:${BUILD_TAG}
    shell: bash
  - name: Run command 1
    run: echo "$REGISTRY_CRED_PSW" | docker login ${REGISTRY} -u "$REGISTRY_CRED_USR" --password-stdin
    shell: bash
  - name: Run command 2
    run: echo $REGISTRY_CRED_PSW
    shell: bash
