name: Build & Push Docker Image Action
description: Enhanced composite action for Build & Push Docker Image stage with comprehensive Jenkins feature support
inputs:
  docker-username:
    description: Docker registry username
    required: 'true'
  docker-password:
    description: Docker registry password
    required: 'true'
  registry-cred-username:
    description: Registry credential username for login command
    required: 'false'
  registry-cred-password:
    description: Registry credential password for login command
    required: 'false'
  registry:
    description: Docker registry URL
    required: false
    default: docker.io
  image-name:
    description: Docker image name
    required: true
  build-tag:
    description: Docker build tag
    required: false
    default: latest
runs:
  using: composite
  steps:
  - name: Login to DockerHub
    uses: docker/login-action@v3
    with:
      username: ${{ inputs.docker-username }}
      password: ${{ inputs.docker-password }}
  - name: Build Docker image
    run: docker build -t ${{ inputs.image-name }}:${{ inputs.build-tag }} .
    shell: bash
  - name: Build Docker image
    run: docker build -t ${{ inputs.image-name }}:${{ inputs.build-tag }} .
    shell: bash
  - name: Push Docker image
    run: docker push ${{ inputs.image-name }}:${{ inputs.build-tag }}
    shell: bash
  - name: Run command 1
    run: echo "$REGISTRY_CRED_PSW" | docker login ${{ inputs.registry }} -u "$REGISTRY_CRED_USR" --password-stdin
    shell: bash
  - name: Run command 2
    run: echo $REGISTRY_CRED_PSW
    shell: bash
