name: Build & Push Docker Image Action
description: Enhanced composite action for Build & Push Docker Image stage with comprehensive Jenkins feature support
inputs:
  docker-username:
    description: "DockerHub Username"
    required: true
  docker-password:
    description: "DockerHub Password"
    required: true
  image:
    description: "Full image name (registry/repo:tag)"
    required: true
runs:
  using: composite
  steps:
    - name: Log in to Docker
      run: echo "${{ inputs.docker-password }}" | docker login -u "${{ inputs.docker-username }}" --password-stdin
      shell: bash

    - name: Build Docker image
      run: docker build -t ${{ inputs.image }} .
      shell: bash

    - name: Push Docker image
      run: docker push ${{ inputs.image }}
      shell: bash


