name: Static Code Analysis (SonarQube) Action
description: Enhanced composite action for Static Code Analysis (SonarQube) stage with comprehensive Jenkins feature support
inputs:
  sonar-token:
    description: SonarQube authentication token
    required: 'true'
  sonar-host-url:
    description: SonarQube server URL
    required: 'true'
runs:
  using: composite
  steps:
  - name: SonarQube Scan
    uses: sonarsource/sonarqube-scan-action@master
    env:
      SONAR_TOKEN: ${{ inputs.sonar-token }}
      SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
    with:
      projectKey: j2github
      projectName: j2github
  - name: Run SonarQube analysis
    run: mvn admin:Adminsonar@12345  -Dsonar.projectKey=${params.APP_NAME}  -Dsonar.projectName=${params.APP_NAME}  -Dsonar.projectVersion=${BUILD_TAG}
    shell: bash
 
