name: Static Code Analysis (SonarQube) Action
description: Enhanced composite action for Static Code Analysis (SonarQube) stage with comprehensive Jenkins feature support
inputs:
  sonar-token:
    description: SonarQube authentication token
    required: 'true'
  sonar-host-url:
    description: SonarQube server URL
    required: 'true'
runs:
  using: composite
  steps:
  - name: SonarQube Scan
    uses: sonarsource/sonarqube-scan-action@master
    env:
      SONAR_TOKEN: ${{ inputs.sonar-token }}
      SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
    with:
      # projectKey: j2github
      # projectName: j2github
     projectBaseDir:
     args:>
      -Dsonar.projectKey=j2github  
      -Dsonar.projectName=j2github  
      -Dsonar.projectVersion=${{ github.run_number }}
 
