name: Static Code Analysis (SonarQube) Action
description: Enhanced composite action for Static Code Analysis (SonarQube) stage with comprehensive Jenkins feature support
inputs: {}
runs:
  using: composite
  steps:
  - name: SonarQube Scan
    uses: sonarqube-scan-action@master
    with:
      projectKey: ${params.APP_NAME}
      projectName: ${params.APP_NAME}
  - name: Run SonarQube analysis
    run: mvn sonar:sonar  -Dsonar.projectKey=${params.APP_NAME}  -Dsonar.projectName=${params.APP_NAME}  -Dsonar.projectVersion=${BUILD_TAG}
    shell: bash
    
