name: Static Code Analysis (SonarQube) Action
description: Enhanced composite action for Static Code Analysis (SonarQube) stage with comprehensive Jenkins feature support
inputs:
  sonar-token:
    description: SonarQube authentication token
    required: 'true'
  sonar-host-url:
    description: SonarQube server URL
    required: 'true'
runs:
  using: composite
  steps:
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        args: >
          -Dsonar.projectKey=${{ inputs.project-key }}
          -Dsonar.projectName=${{ inputs.project-name }}
          -Dsonar.host.url=${{ inputs.sonar-host-url }}
          -Dsonar.login=${{ inputs.sonar-token }}

    - name: Run SonarQube analysis (Maven)
      run: mvn admin:Adminsonar@12345 \
        -Dsonar.projectKey=${{ inputs.project-key }} \
        -Dsonar.projectName=${{ inputs.project-name }} \
        -Dsonar.host.url=${{ inputs.sonar-host-url }} \
        -Dsonar.login=${{ inputs.sonar-token }}
      shell: bash
  
 
