name: Static Code Analysis (SonarQube) Action
description: Enhanced composite action for Static Code Analysis (SonarQube) stage with comprehensive Jenkins feature support
inputs:
  sonar-token:
    description: SonarQube authentication token
    required: 'true'
  sonar-host-url:
    description: SonarQube server URL
    required: 'true'
runs:
  using: composite
  steps:
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      

    - name: Run SonarQube analysis (Maven)
      run: mvn clean verify sonar:sonar \
        -Dsonar.projectKey=j2github \
        -Dsonar.projectName='j2github' \
        -Dsonar.host.url=http://10.138.77.59:9000 \
        -Dsonar.token=sqp_08b91dcc344b282291cba597f58113d812277649
      shell: bash
  
 
